### ISSUE TITLE
Add shared-data for things like auth

### ISSUE THREAD

**Issue by tmartin314** [devato/inertia_phoenix#1]
Add shared data that will be loaded on every request for auth and other data.

https://inertiajs.com/shared-data

**Comment by tmartin314** [comment]
@zimt28 Any suggestions on how to implement this?

**Comment by zimt28** [comment]
The only sane way I see to get something similar is a function that adds a key/value pair to `conn.assigns.inertia_props` or similar and `InertiaPhoenix.Controller.render_inertia` merges these with regular props. This way data could be added from plugs etc.

**Comment by tmartin314** [comment]
That makes sense,  the developer will just create a custom plug.  It's not much different from the way the official rails adapter handles it.  Gonna try to stick to their naming of things for consistency.

**Comment by bigx333** [comment]
conn.private should be used for this I believe?:

This storage is meant to be used by libraries and frameworks to avoid writing to the user storage (the :assigns field). It is recommended for libraries/frameworks to prefix the keys with the library name.:

https://hexdocs.pm/plug/Plug.Conn.html#put_private/3

**Comment by tmartin314** [comment]
Thanks @bigx333.  Good thinking.

Let me know if anyone wants to stab at this.

**Comment by zimt28** [comment]
@bigx333 Yes, much better! Totally forgot about it :)

**Comment by zimt28** [comment]
@tmartin314 On it, will send a PR tomorrow

**Comment by tmartin314** [comment]
@zimt28 great!  I'll jump on something else

**Comment by zimt28** [comment]
The Laravel implementation uses strings as keys, eg `Inertia::share('auth.user', $user)`. I guess `auth.user` will then be used to create something like nested maps to make it accessible via `$page.auth.user.name`. 

I'd prefer atom keys over binary, but we cannot create the nested maps like Laravel then, which I don't see as an issue. What's your opinion on this, should we support atoms, binaries or both?

**Comment by tmartin314** [comment]
I think we may need to support both as some data might be dynamically generated.  I'm pretty sure Jason will encode them the same way,  right?

**Comment by tmartin314** [comment]
I agree,  atoms are preferable.

**Comment by tmartin314** [comment]
@zimt28 I'm also starting to wonder if we need to use private as the user will be configuring the pieces of data themselves.

**Comment by tmartin314** [comment]
@zimt28 This was added in [v0.2.0](https://github.com/devato/inertia_phoenix/releases/tag/0.2.0)

Thanks alot! 
cc: @bigx333

**Comment by zimt28** [comment]
@tmartin314 Sorry for the missing PR, different time zone and I went to bed first 😄 Thanks for merging the code!
