### ISSUE TITLE
Add partial reloads

### ISSUE THREAD

**Issue by tmartin314** [devato/inertia_phoenix#4]
https://inertiajs.com/requests#partial-reloads

> The only option allows you to request a subset of the props (data) from the server on subsequent visits to the same page. This feature is called partial reloads, and can be a helpful performance optimization if it's acceptable that some page data becomes stale. For partial reloads to be effective, be sure to use lazy evaluation server-side.

**Comment by bigx333** [comment]
I'm busy extracting this feature from a personal project and will add a pull request :)

**Comment by tmartin314** [comment]
Added in #11 by @bigx333 thanks!
