### ISSUE TITLE
Haha, I was looking for this last week

### ISSUE THREAD

**Issue by totaltrash** [devato/inertia_phoenix#6]
Looks like we had the same idea at the same time! I started knocking something together on the weekend (https://github.com/totaltrash/test_phoenix_inertia), pulled out the Inertia stuff into a library just now (https://github.com/ifixsystems-au/inertia-phoenix), had a look on Hex, and found you've been busy on the weekend too!

Looking good, pretty excited about Inertia and Elixir (I'm not an Elixir developer, I was just looking for a project to do on the weekend).

**Comment by tmartin314** [comment]
@totaltrash Great! Maybe we can combine our efforts?  
I see you have the asset version plug ready, mind if I pull that into this project?
